### ISSUE TITLE
Terminar os Requisitos Não Funcionais [rnf.md]

### ISSUE THREAD

**Issue by guievbs** [guievbs/agro-connect-2024.1#10]
## Desenvolver os requisitos não funcionais da aplicação

- Os requisitos funcionais devem ser claros, concisos e abrangentes o suficiente

- É importante que os requisitos sejam feitos no arquivo [rnf.md](https://github.com/guievbs/agro-connect-2024.1/blob/main/Requisitos%20de%20Usu%C3%A1rio/rnf.md) de forma a permitir uma fácil revisão

Aqueles que já elaboraram seus requisitos, por favor, deixem uma mensagem abaixo avisando.

- @Celsolf 
- @gabrielflorianoo 
- @DiegoOtani 
- @robsonldcarvalho 
- @eduzindejesus 
- @JoaoBUC
- @MatheusMari

**Comment by gabrielflorianoo** [comment]
Ja fiz os meus requisitos não funcionais

**Comment by DiegoOtani** [comment]
Já fiz os requisitos

**Comment by robsonldcarvalho** [comment]
feito

**Comment by guievbs** [comment]
Conferi  o progresso e vi que todos participaram
